### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoevent-java#45]
There should be releases in this repository that correspond to the releases of GeoEvent Extension.

- [ ] 10.2
- [ ] 10.2.1
- [ ] 10.2.2
- [ ] 10.3
- [ ] 10.3.1

**Comment by pHill5136** [comment]
We do not want to replicate code for each release. The only reason we separate between 10.2 and 10.3 is that the components are not compatible because of api changes affect backward compatibility.

There is nothing that we built at 10.2 that can not be built at 10.2.2 (or at 10.2.2. that cannot be built at 10.2). Also everything built at 10.3.0 can be built at 10.3.1 (and vice versa.). The api changes were only between 10.2.x and 10.3.x. I try to keep the lowest version number for which a component will work.

**Comment by pHill5136** [comment]
Now that 10.3.1 is released I will modify the version numbers on the pom.xml files so that they will point to 10.3.1. The folder structure is such that the version is referenced in directory paths. If users have 10.3.0 installed on their system they will have to modify the version manually in the pom.xml for maven to find dependency libraries. For those users still using 10.2 and prior they should reference the 10.2.x components offered as a legacy. Because of some changes in the api between 10.2 and 10.3 10.2 components will not work in 10.3.

**Comment by jrweakland** [comment]
@pHill5136 - We will need to have releases for 10.2 and 10.3 at a minimum.

**Comment by pHill5136** [comment]
We have releases for 10.2, 10.30, 10.31
